### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by ThaWade** [YouMadCraft/YouMadCraft-1.7Bugs#1]
Log in and before I can move, Minecraft crashes.

http://pastebin.com/tuj0bkgu

**Comment by UnRealDinnerbone** [comment]
It looks like there a mob crashing you try making a new world with a new seed Please post results back hear

**Comment by ThaWade** [comment]
That worked. Playing it now, thanks.

**Comment by ThaWade** [comment]
I really need to learn how to read crash reports. Another crash for you. I got to play 2 hours this time though. :) 
http://pastebin.com/Yc1QhsC5

**Comment by UnRealDinnerbone** [comment]
Ok Can You give the crash report for the world  :)

**Comment by ThaWade** [comment]
No I can no longer log into the world. It does the loading terrain thing and then crashes now.

When it crashed the Blood moon was out. And I right clicked on either the bed or a vanilla furnace with a tinkers construct pickaxe in my hand.

**Comment by UnRealDinnerbone** [comment]
ok

**Comment by ThaWade** [comment]
Ok back again. This time around... Punching a spruce wood tree. Started getting attacked by termites. Killed some of the termites. Got blind reward bag. Opened it. got some type of boots(They were blue and hideous). put those on. killed the rest of the termites.  Started walking back to the tree I was punching. Crash about 5 blocks from the tree.(You probably didn't to know all that but, couldn't hurt I don't guess.)
http://pastebin.com/qJTmnJCL

It let me log back in and then crashed again. Including that crash report to. (For comparison?)
http://pastebin.com/jG5C206i

**Comment by UnRealDinnerbone** [comment]
i dont know there some mob that spawning that crashes most people i will look in to it

**Comment by UnRealDinnerbone** [comment]
ok try remove Infernal Mobs from the mods i think it do something wrong

**Comment by ThaWade** [comment]
Removed Infernal Mobs. Created a new world. Killed some more termites. Then crash.
http://pastebin.com/fD09U7Ma

**Comment by UnRealDinnerbone** [comment]
The only way for me to fix it is if you could send me your world save

**Comment by ThaWade** [comment]
I've created another world and it's working so far (30 minutes). The above post I re-created the world. That may have had some thing to do with it.  If you'd like the world save any way, I could send it to you.  And let me know if you need the entire world folder or just a file or two from within it.

**Comment by UnRealDinnerbone** [comment]
iwpuld still like the save cause they outher bug for this pack is the same problme

**Comment by UnRealDinnerbone** [comment]
also im going to try and update of all the mods to see if it fixes it Update Comeing soon

**Comment by ThaWade** [comment]
Would you prefer .7z or .zip file?

**Comment by UnRealDinnerbone** [comment]
Zip

**Comment by UnRealDinnerbone** [comment]
also update tommory

**Comment by ThaWade** [comment]
World Save - https://drive.google.com/file/d/0B7pSkqPMZSNVX1VEcEFrcEV0T3c/view?usp=sharing
Also, I couldn't find "tommory" through the curse client or google or in my mods folder.

**Comment by UnRealDinnerbone** [comment]
I mean I'm going to update the pack tommoary

**Comment by ThaWade** [comment]
Ohhh, sorry I thought you meant for me to update a mod. Any who it's tomorrow, for future reference. Thanks for the back and forth I appreciate it.

**Comment by UnRealDinnerbone** [comment]
look at when I get home from school

**Comment by UnRealDinnerbone** [comment]
Also accept me friend request on the curse Voice client

**Comment by UnRealDinnerbone** [comment]
Fixed It Was OreSpawn Sadlly it will be removed from the pack do to it's bugs
