### ISSUE TITLE
Hostile mob spawn

### ISSUE THREAD

**Issue by Chaoschicken** [YouMadCraft/YouMadCraft-1.7Bugs#2]
First couple nights there were zombies, skeletons and creepers. I had one blood moon and since then have not had a single hostile mob spawn. Maybe too many passives like ants and such?? Not sure what happened but something is messed up.

**Comment by UnRealDinnerbone** [comment]
Try /Cofh killall which will kill all the mobs and post back if it works or it does not work

**Comment by Chaoschicken** [comment]
that fixed it but then I started shooting skeletons with Ultimate bow and crashed/corrupted game. RIP

**Comment by UnRealDinnerbone** [comment]
I don't know what is making that happen can you give me a crash report.

**Comment by Chaoschicken** [comment]
http://pastebin.com/1pLiqfbg

**Comment by UnRealDinnerbone** [comment]
Remove Inferal Mobs :+1: it work
then and whont happned i hope

**Comment by UnRealDinnerbone** [comment]
i fixed it but no more OreSpawn it was making the game crash :(
